### ISSUE TITLE
Can SecureCookie be used concurrently?

### ISSUE THREAD

**Issue by Komosa** [gorilla/securecookie#14]
I'm asking for general case, without any other assumptions.

If not, what is the reason?

**Comment by fluffysquirrels** [comment]
Looking at the source it's not safe for concurrent use without extra locking or other restrictions. E.g. [`func (s *SecureCookie) BlockFunc(f func([]byte) (cipher.Block, error)) *SecureCookie`](https://github.com/gorilla/securecookie/blob/5f171f42328bdd573211bb82bdee8f259c4c61ae/securecookie.go#L115-L124) modifies fields without locking.

It's very common for frameworks to expect most types to be used only within a single request and therefore not to make them thread-safe (e.g. this [Java servlet API's Cookie implementation](http://grepcode.com/file/repo1.maven.org/maven2/javax.servlet/servlet-api/2.4/javax/servlet/http/Cookie.java#Cookie.setValue%28java.lang.String%29) modifies properties without locks, and the [Microsoft ASP.NET HttpCookie class documentation](https://msdn.microsoft.com/en-us/library/system.web.httpcookie(v=vs.140).aspx) states that instances are not thread safe). Not providing thread safety cuts down on the implementation complexity, and can make the code faster in single threaded use. To me this is the right trade off and is what I assume about types unless told otherwise, but perhaps more types should be documented explicitly as 'not thread-safe'.

I'd strongly advise **not** using an instance of SecureCookie concurrently, unless you've profiled your app and found it's a bottleneck in a section of code that must be high performance. Otherwise [The Go Memory Model](https://golang.org/ref/mem) is a good reference, but as it says:

> If you must read the rest of this document to understand the behavior of your program, you are being too clever.
> 
> Don't be clever.

**Comment by fluffysquirrels** [comment]
Hmmm, I've just had another think about this.

For my use of this type, I want to load my keys from disk with [sync.Once](http://golang.org/pkg/sync/#Once) on startup into a SecureCookie instance and then re-use that between all my requests. I think this will be safe with the current SecureCookie implementation, but it'd be good to see a documented guarantee that this will continue to work.

Is that the same thought you had, @Komosa?

**Comment by kisielk** [comment]
@fluffysquirrels I don't think reusing the same securecookie between requests will be safe, at least I don't think it was designed with that in mind. You can always loading your keys once and use them as arguments to all the SecureCookie instances you create, there shouldn't be any additional overhead (it's just a slice after all)

**Comment by Komosa** [comment]
Thanks for answers. I finally choose making new instance per each request. But, for mathematical functions like encryption/decryption it will be nice to be _pure_ :)

@fluffysquirrels why you just don't load something from disk before starting your handler? Reason is to minimize startup or downtime?

**Comment by kisielk** [comment]
I agree, if I was designing the package from scratch it would probably work differently :)
