### ISSUE TITLE
How to handle error "securecookie: expired timestamp"

### ISSUE THREAD

**Issue by ahmetb** [gorilla/securecookie#44]
I get error `securecookie: expired timestamp` even though I don't set an expiration date on the cookie. (I suspect there's a date in the encrypted cookie.) Here is my logic:

```go
	co, err := sc.Encode("user", user.ID)
	if err != nil {
		return errors.Wrap(err, "failed to encode the token")
	}

	http.SetCookie(w, &http.Cookie{
		Name:  "user",
		Path:  "/",
		Value: co,
	})
```

What am I supposed to do with this error?

The `errTimestampExpired` is not exported from the package, so that doesn't give me a good way to check whether an error is indeed expiration error. What should a server do when they get this error? Clear cookies to unblock the user?

**Comment by elithrar** [comment]
You can change the MaxAge on the securecookie instance yourself:
http://www.gorillatoolkit.org/pkg/securecookie#SecureCookie.MaxAge

**Comment by buchdag** [comment]
This error still happens with an extended MaxAge (one month in my case) and the question of how to properly handle it still remains.

**Comment by korrasami** [comment]
@elithrar If my code get this error, how should it handle it? CookieStore would return a nil Session, I don't see any method in CookieStore to clear it.

**Comment by dsringari** [comment]
The point of this thread is to express that there's no good way to handle or check if the cookie decode failed due to an expired timestamp.

The reason that we may need to know if the cookie decode failed due to an expired timestamp is to return some special response to the client in order to trigger re-authentication. E.g. Returning http status code 440

Can we revisit this thread and answer the above question? Namely how can I check or match against an errTimestampExpired error?

**Comment by lily1110** [comment]
hi @buchdag I assume you set the MaxAge by setting `sessionStore.Options `
```
        sessionStore := sessions.NewCookieStore([]byte(secret))
	sessionStore.Options = &sessions.Options{
		Path:     config.Path,
		MaxAge:   config.MaxAge,
		HttpOnly: config.HTTPOnly,
		Secure:   config.Secure,
	}
```
In the function NewCookieStore, it sets the default MaxAge and it will not work by setting it to Options
https://github.com/gorilla/sessions/blob/a6a8e49c83a2dba9cf7f486feb2662d6439851f2/store.go#L49
```
func NewCookieStore(keyPairs ...[]byte) *CookieStore {
	cs := &CookieStore{
		Codecs: securecookie.CodecsFromPairs(keyPairs...),
		Options: &Options{
			Path:   "/",
			MaxAge: 86400 * 30,
		},
	}

	cs.MaxAge(cs.Options.MaxAge)
	return cs
}
```
NewCookieStore will set MaxAge using the default one,  86400 * 30 instead of your options.MaxAge.
`MaxAge` will set the `maxAge` for each `Codecs`. Only setting `option` will not change the `Codecs.MaxAge`. You could read it for more details.
https://github.com/gorilla/sessions/blob/a6a8e49c83a2dba9cf7f486feb2662d6439851f2/store.go#L115

Hope this could give you some help.
